[profile.default]
cache_path = "contracts-cache"
libs = ["node_modules", "lib"]
out = 'contracts-out'
remappings = ['ds-test/=lib/ds-test/src/']
src = 'contracts'

# See more config options https://github.com/gakonst/foundry/tree/master/config
